import { readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"
import { defineConfig, type Plugin } from "vite"
import react from "@vitejs/plugin-react"
import { viteSingleFile } from "vite-plugin-singlefile"

/**
 * Vite plugin that auto-embeds the built single-file HTML into
 * src/dashboard/assets.ts after production builds.
 *
 * Replaces the separate `scripts/embed-dashboard.ts` step so that
 * `bun run dashboard:build` alone produces both dist/index.html AND assets.ts.
 */
function embedDashboard(): Plugin {
  return {
    name: "ignition-embed-dashboard",
    apply: "build",
    closeBundle() {
      const distPath = resolve(__dirname, "dist", "index.html")
      const outPath = resolve(__dirname, "..", "assets.ts")

      let html = ""
      try {
        html = readFileSync(distPath, "utf-8")
      } catch {
        // dist/ not built yet — write empty placeholder
      }

      const escaped = html.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("$", "\\$")

      const output = `// AUTO-GENERATED by vite build — do not edit\nexport const DASHBOARD_HTML = \`${escaped}\`\n`

      writeFileSync(outPath, output)

      const bytes = new TextEncoder().encode(output).length
      const label = html ? `embedded ${(bytes / 1024).toFixed(1)} KB` : "empty placeholder"
      console.log(`wrote src/dashboard/assets.ts (${label})`)
    },
  }
}

export default defineConfig({
  root: ".",
  plugins: [react(), viteSingleFile(), embedDashboard()],
  server: {
    port: 5173,
    proxy: {
      "/ws": {
        target: "ws://127.0.0.1:9090",
        ws: true,
      },
      "/api": {
        target: "http://127.0.0.1:9090",
        changeOrigin: true,
      },
    },
  },
  build: {
    outDir: "dist",
    emptyOutDir: true,
  },
})
