/**
 * File roundtrip recipe: exercise file and directory resources end-to-end.
 *
 * Creates temp files with different methods (content, template), verifies them,
 * then removes everything. No permanent server changes.
 *
 * Usage:
 *   ignition check examples/file-roundtrip.ts admin@10.0.1.5
 *   ignition run   examples/file-roundtrip.ts admin@10.0.1.5
 *
 *   # Pass custom vars:
 *   ignition run examples/file-roundtrip.ts admin@10.0.1.5 --var greeting="Hey there"
 */

import type { ExecutionContext, TemplateContext } from "@grovemotorco/ignition"
import { createResources } from "@grovemotorco/ignition"

export const meta = {
  description: "File and directory resource roundtrip test",
  tags: ["test", "file", "directory"],
}

const configTemplate = (vars: TemplateContext): string => {
  const greeting = (vars.greeting as string) ?? "Hello from Ignition"
  const host = (vars.host_name as string) ?? "unknown"
  return `# Generated by Ignition file-roundtrip test
# Host: ${host}
# This file should be cleaned up automatically.

message = "${greeting}"
env = "${(vars.env as string) ?? "test"}"
`
}

export default async function (ctx: ExecutionContext): Promise<void> {
  const { exec, file, directory } = createResources(ctx)
  const base = "/tmp/ignition-roundtrip"

  // --- Create structure ---

  await directory({ path: base, mode: "755" })
  await directory({ path: `${base}/conf`, mode: "755" })
  await directory({ path: `${base}/data`, mode: "755" })

  // Plain content file
  await file({
    path: `${base}/data/plain.txt`,
    content: "This is a plain text file created by Ignition.\n",
    mode: "644",
  })

  // Templated config file (uses vars from inventory or --var flags)
  await file({
    path: `${base}/conf/app.conf`,
    template: configTemplate,
    mode: "644",
  })

  // Multi-line content file
  await file({
    path: `${base}/data/lines.txt`,
    content: ["line 1: alpha", "line 2: bravo", "line 3: charlie", "line 4: delta", ""].join("\n"),
    mode: "644",
  })

  // --- Verify ---

  await exec({ command: `ls -laR ${base}` })
  await exec({ command: `cat ${base}/conf/app.conf` })
  await exec({ command: `wc -l ${base}/data/lines.txt` })

  // --- Idempotence check: re-apply same file (should report "ok") ---

  await file({
    path: `${base}/data/plain.txt`,
    content: "This is a plain text file created by Ignition.\n",
    mode: "644",
  })

  // --- Cleanup (reverse order) ---

  await file({ path: `${base}/data/lines.txt`, state: "absent" })
  await file({ path: `${base}/data/plain.txt`, state: "absent" })
  await file({ path: `${base}/conf/app.conf`, state: "absent" })
  await directory({ path: `${base}/conf`, state: "absent" })
  await directory({ path: `${base}/data`, state: "absent" })
  await directory({ path: base, state: "absent" })
}
