/**
 * Embed the dashboard single-file HTML into a TypeScript module.
 *
 * Reads the Vite-built `dist/index.html` (a single self-contained file produced
 * by vite-plugin-singlefile) and writes `src/dashboard/assets.ts` exporting the
 * HTML as a string constant.
 *
 * If `dist/index.html` doesn't exist (no build yet), writes an empty placeholder
 * so that type-checking works without a prior dashboard build.
 *
 * Usage: bun run scripts/embed-dashboard.ts
 */

import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

const scriptDir = dirname(fileURLToPath(import.meta.url))
const distPath = join(scriptDir, "..", "src", "dashboard", "ui", "dist", "index.html")
const outPath = join(scriptDir, "..", "src", "dashboard", "assets.ts")

let html = ""
try {
  html = await Bun.file(distPath).text()
} catch {
  // dist/ not built yet — write empty placeholder
}

// Escape backticks and dollar signs for template literal safety
const escaped = html.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("$", "\\$")

const output = `// AUTO-GENERATED by scripts/embed-dashboard.ts — do not edit
export const DASHBOARD_HTML = \`${escaped}\`
`

await Bun.write(outPath, output)

const bytes = new TextEncoder().encode(output).length
const label = html ? `embedded ${(bytes / 1024).toFixed(1)} KB` : "empty placeholder"
console.log(`wrote src/dashboard/assets.ts (${label})`)
