/**
 * Ensure src/dashboard/assets.ts exists so that TypeScript and runtime
 * imports resolve on a fresh clone (before the dashboard has been built).
 *
 * The real file is generated by `bun run dashboard:build` via the Vite
 * embedDashboard plugin.  This script only writes an empty placeholder
 * when the file is missing — it never overwrites an existing build.
 *
 * Runs automatically via the `prepare` hook after `bun install`.
 */

import { existsSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"

const assetsPath = resolve(import.meta.dir, "..", "src", "dashboard", "assets.ts")

if (!existsSync(assetsPath)) {
  writeFileSync(
    assetsPath,
    '// AUTO-GENERATED stub — run `bun run dashboard:build` to embed\nexport const DASHBOARD_HTML = ""\n',
  )
  console.log("created src/dashboard/assets.ts (stub)")
}
